feat: ci/cd 수정

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -67,25 +67,34 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           port: ${{ secrets.SSH_PORT }}
           script: |
+            set -e
             docker pull lushlife99/nhn-book-coupon:${{ github.sha }}
             if [ "$(docker ps -aq --filter "name=book-coupon-api-instance-1")" ]; then
               docker stop book-coupon-api-instance-1 || true
               docker rm -f book-coupon-api-instance-1 || true
             fi
-              docker run --name book-coupon-api-instance-1 --network nhn-book-store-network -p 8086:8086 -e SPRING_PROFILES_ACTIVE=instance1 -d lushlife99/nhn-book-coupon:${{ github.sha }}
+            docker run --name book-coupon-api-instance-1 --network nhn-book-store-network -p 8086:8086 -e SPRING_PROFILES_ACTIVE=instance1 -d lushlife99/nhn-book-coupon:${{ github.sha }}
+            docker logs -f book-coupon-api-instance-1
 
-
-      - name: Deploy to Second Instance
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SSH_IP }}
-          username: ${{ secrets.SSH_ID }}
-          key: ${{ secrets.SSH_KEY }}
-          port: ${{ secrets.SSH_PORT }}
-          script: |
-            docker pull lushlife99/nhn-book-coupon:${{ github.sha }}
-            if [ "$(docker ps -aq --filter "name=book-coupon-api-instance-2")" ]; then
-              docker stop book-coupon-api-instance-2 || true
-              docker rm -f book-coupon-api-instance-2 || true
+      - name: Check First Instance via Eureka
+        run: |
+          START_TIME=$(date +%s)
+          while : ; do
+            RESPONSE=$(curl -s -H "Accept: application/xml" http://${{ secrets.EUREKA_USERNAME }}:${{ secrets.EUREKA_PASSWORD }}@nhn24.store/eureka/eureka/instances/book-coupon-api-instance-1)
+            if [ -z "$RESPONSE" ]; then
+              echo "Error: Empty response from Eureka server."
+              exit 1
             fi
-              docker run --name book-coupon-api-instance-2 --network nhn-book-store-network -p 8087:8087 -e SPRING_PROFILES_ACTIVE=instance2 -d lushlife99/nhn-book-coupon:${{ github.sha }}
+            STATUS=$(echo "$RESPONSE" | xmllint --xpath "string(//status)" - 2>/dev/null)
+            if [ "$STATUS" == "UP" ]; then
+              echo "First instance is healthy and UP."
+              break
+            fi
+            CURRENT_TIME=$(date +%s)
+            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
+            if [ $ELAPSED_TIME -ge 180 ]; then
+              echo "First instance is not healthy within 3 minutes. Aborting deployment."
+              exit 1
+            fi
+            sleep 10
+          done
